import z, { type ZodRawShape } from "zod"
import { STAGE_MOVE_FILE_OR_FOLDER_INPUT_DESCRIBE__FROM, STAGE_MOVE_FILE_OR_FOLDER_INPUT_DESCRIBE__TO, STAGE_MOVE_FILE_OR_FOLDER_OUTPUT_DESCRIBE__IDENTIFIER, STAGE_MOVE_FILE_OR_FOLDER_OUTPUT_DESCRIBE__PATH, STAGE_MOVE_FILE_OR_FOLDER_OUTPUT_DESCRIBE__CONTENTS, STAGE_MOVE_FILE_OR_FOLDER_OUTPUT_DESCRIBE__CONTENTS__ENTRY } from "../constants/descriptions"

export const StageMoveFileOrFolderInput: ZodRawShape = {
  from: z.string().describe(STAGE_MOVE_FILE_OR_FOLDER_INPUT_DESCRIBE__FROM),
  to: z.string().describe(STAGE_MOVE_FILE_OR_FOLDER_INPUT_DESCRIBE__TO)
}

export const StageMoveFileOrFolderOutput: ZodRawShape = {
  identifier: z.string().describe(STAGE_MOVE_FILE_OR_FOLDER_OUTPUT_DESCRIBE__IDENTIFIER),
  path: z.string().describe(STAGE_MOVE_FILE_OR_FOLDER_OUTPUT_DESCRIBE__PATH),
  contents: z.array(
    z.string().describe(STAGE_MOVE_FILE_OR_FOLDER_OUTPUT_DESCRIBE__CONTENTS__ENTRY)
  ).nullable().describe(STAGE_MOVE_FILE_OR_FOLDER_OUTPUT_DESCRIBE__CONTENTS),
}
