import z, { type ZodRawShape } from "zod"
import { STAGE_PENDING_FOLDER_RENAME_INPUT_DESCRIBE__FROM, STAGE_PENDING_FOLDER_RENAME_INPUT_DESCRIBE__TO, STAGE_PENDING_FOLDER_RENAME_OUTPUT_DESCRIBE__IDENTIFIER, STAGE_PENDING_FOLDER_RENAME_OUTPUT_DESCRIBE__ROOT_FOLDER, STAGE_PENDING_FOLDER_RENAME_OUTPUT_DESCRIBE__CONTENTS__ENTRY, STAGE_PENDING_FOLDER_RENAME_OUTPUT_DESCRIBE__CONTENTS } from "../shape-metadata"

export const StagePendingFolderRenameInput: ZodRawShape = {
  from: z.string().describe(STAGE_PENDING_FOLDER_RENAME_INPUT_DESCRIBE__FROM),
  to: z.string().describe(STAGE_PENDING_FOLDER_RENAME_INPUT_DESCRIBE__TO)
}

export const StagePendingFolderRenameOutput: ZodRawShape = {
  identifier: z.string().describe(STAGE_PENDING_FOLDER_RENAME_OUTPUT_DESCRIBE__IDENTIFIER),
  rootFolder: z.string().describe(STAGE_PENDING_FOLDER_RENAME_OUTPUT_DESCRIBE__ROOT_FOLDER),
  contents: z.array(
    z.string().describe(STAGE_PENDING_FOLDER_RENAME_OUTPUT_DESCRIBE__CONTENTS__ENTRY)
  ).describe(STAGE_PENDING_FOLDER_RENAME_OUTPUT_DESCRIBE__CONTENTS),
}
